apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-latency-example
  namespace: application
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: sre-abc-training-app
  delay:
    latency: "1000ms"
    correlation: "100"
    jitter: "100ms"
  duration: "30s"
  scheduler:
    cron: "@every 3m"