apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-delete-example
  namespace: application
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: sre-abc-training-app
  duration: "30s"
  scheduler:
    cron: "@every 2m"