apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-rollback-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-rollback-app
  template:
    metadata:
      labels:
        app: sre-rollback-app
    spec:
      containers:
        - name: app
          image: rsergio07/sre-rollback-demo:v1
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: sre-rollback-service
spec:
  selector:
    app: sre-rollback-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
