apiVersion: v1
kind: Service
metadata:
  name: sre-abc-training-service
spec:
  type: NodePort
  selector:
    app: sre-abc-training-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007 # You can specify a different NodePort if desired
